export { default as NavbarDashboard } from './Dashboard/Navbar-Dashboard';
export { default as Navbar } from './Navbar/Navbar';
export { default as Hero } from './Home/Hero';
export { default as About } from './Home/About';
export { default as Benefits} from './Home/Benefits';
export { default as LoginForm} from './Form/LoginForm';
export { default as AuthOptions} from './Form/AuthOptions';
export { default as RegisterForm} from './Form/RegisterForm';
export { default as MenuDashboard } from './Dashboard/Menu-Dashboard';
export { default as IntroDashboard } from './Dashboard/Intro-Dashboard';
export { default as RegisterClient } from './Dashboard/DashboardRoute/Route-Register-Client/RegisterClient';
export { default as SelectClient } from './Dashboard/DashboardRoute/ClientsAndPets/SelectClient';
export { default as ListClients } from './Dashboard/DashboardRoute/ClientsAndPets/List-Clients';
export { default as EditClients } from './Dashboard/DashboardRoute/ClientsAndPets/EditClients';
export { default as EditClient } from './Dashboard/EditClient';